;
; ASCOM Lumix Camera driver - 64-bit installer
; Originally generated by the ASCOM Driver Installer Script Generator 6.4.0.0
;
; Build with:  ISCC "ASCOM.Lumix.Camera Setup.iss"
; Requires the x64 Release build first:
;   msbuild LumixCamera\LumixCamera.vbproj -p:Configuration=Release -p:Platform=x64
;
; This is the build that supports USB: the bundled Lumix SDK (native\x64\Lmxptpif.dll)
; is x64 only. See the 32-bit script for what that build can and cannot do.
;

#define AppVer "8.0.0"
; Paths are relative to this .iss file so the script builds on any machine.
#define RepoRoot AddBackslash(SourcePath) + "..\"
#define BinDir   AddBackslash(SourcePath) + "bin\x64\Release\"

[Setup]
AppID={{77b4d898-3116-40a5-91d4-4c41ff123d93}
AppName=ASCOM Lumix Camera Driver
AppVerName=ASCOM Lumix Camera Driver {#AppVer} (64-bit)
AppVersion={#AppVer}
AppPublisher=robert hasson <robert_hasson@yahoo.com>
AppPublisherURL=mailto:robert_hasson@yahoo.com
AppSupportURL=http://tech.groups.yahoo.com/group/ASCOM-Talk/
AppUpdatesURL=http://ascom-standards.org/
VersionInfoVersion={#AppVer}
MinVersion=0,6.0
DefaultDirName="{cf}\ASCOM\Camera"
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputBaseFilename="ASCOM.Lumix.Camera Setup"
Compression=lzma
SolidCompression=yes
; 64-bit only: the bundled USB SDK is x64, and a 32-bit host cannot load it.
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
; Put there by Platform if Driver Installer Support selected
WizardImageFile="C:\Program Files (x86)\ASCOM\Developer\Installer Generator\Resources\WizardImage.bmp"
LicenseFile="C:\Program Files (x86)\ASCOM\Developer\Installer Generator\Resources\CreativeCommons.txt"
; {cf}\ASCOM\Uninstall\Camera folder created by Platform, always
UninstallFilesDir="{cf}\ASCOM\Uninstall\Camera\ASCOM.Lumix.Camera"
OutputDir="{#RepoRoot}"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{cf}\ASCOM\Uninstall\Camera\ASCOM.Lumix.Camera"
Name: "{app}\native\x64"

[Files]
Source: "{#BinDir}ASCOM.Lumix.Camera.dll"; DestDir: "{app}"
; USB transport: the managed SDK binding plus the bundled public Lumix SDK. Without
; both of these the driver still runs but every USB mode fails to connect.
Source: "{#BinDir}ASCOM.Lumix.Usb.dll"; DestDir: "{app}"
Source: "{#BinDir}native\x64\Lmxptpif.dll"; DestDir: "{app}\native\x64"
; Editable camera/resolution table (the driver falls back to an embedded copy if absent)
Source: "{#BinDir}cameras.json"; DestDir: "{app}"
; RAW decoding
Source: "{#BinDir}libraw.dll"; DestDir: "{app}"
Source: "{#BinDir}libraw32.dll"; DestDir: "{app}"
; Read-me shown after installation
Source: "{#RepoRoot}README.md"; DestDir: "{app}"; Flags: isreadme
Source: "{#RepoRoot}readme_files\*"; DestDir: "{app}\readme_files\"

; Only for .NET assembly/in-proc drivers.
; NOTE: only the driver assembly is registered. libraw/libraw32 are native DLLs -
; running regasm on them was a no-op that could only ever fail.
[Run]
Filename: "{dotnet4064}\regasm.exe"; Parameters: "/codebase ""{app}\ASCOM.Lumix.Camera.dll"""; Flags: runhidden 64bit; Check: IsWin64

[UninstallRun]
Filename: "{dotnet4064}\regasm.exe"; Parameters: "-u ""{app}\ASCOM.Lumix.Camera.dll"""; Flags: runhidden 64bit; Check: IsWin64

[Code]
const
   REQUIRED_PLATFORM_VERSION = 6.2;    // Set this to the minimum required ASCOM Platform version for this application

//
// Function to return the ASCOM Platform's version number as a double.
//
function PlatformVersion(): Double;
var
   PlatVerString : String;
begin
   Result := 0.0;  // Initialise the return value in case we can't read the registry
   try
      if RegQueryStringValue(HKEY_LOCAL_MACHINE_32, 'Software\ASCOM','PlatformVersion', PlatVerString) then
      begin // Successfully read the value from the registry
         Result := StrToFloat(PlatVerString); // Create a double from the X.Y Platform version string
      end;
   except
      ShowExceptionMessage;
      Result:= -1.0; // Indicate in the return value that an exception was generated
   end;
end;

//
// Before the installer UI appears, verify that the required ASCOM Platform version is installed.
//
function InitializeSetup(): Boolean;
var
   PlatformVersionNumber : double;
 begin
   Result := FALSE;  // Assume failure
   PlatformVersionNumber := PlatformVersion(); // Get the installed Platform version as a double
   If PlatformVersionNumber >= REQUIRED_PLATFORM_VERSION then	// Check whether we have the minimum required Platform or newer
      Result := TRUE
   else
      if PlatformVersionNumber = 0.0 then
         MsgBox('No ASCOM Platform is installed. Please install Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later from http://www.ascom-standards.org', mbCriticalError, MB_OK)
      else
         MsgBox('ASCOM Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later is required, but Platform '+ Format('%3.1f', [PlatformVersionNumber]) + ' is installed. Please install the latest Platform before continuing; you will find it at http://www.ascom-standards.org', mbCriticalError, MB_OK);
end;

// Code to enable the installer to uninstall previous versions of itself when a new version is installed
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  UninstallExe: String;
  UninstallRegistry: String;
begin
  if (CurStep = ssInstall) then // Install step has started
	begin
      // Create the correct registry location name, which is based on the AppId
      UninstallRegistry := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}' + '_is1');
      // Check whether an extry exists
      if RegQueryStringValue(HKLM, UninstallRegistry, 'UninstallString', UninstallExe) then
        begin // Entry exists and previous version is installed so run its uninstaller quietly after informing the user
          MsgBox('Setup will now remove the previous version.', mbInformation, MB_OK);
          Exec(RemoveQuotes(UninstallExe), ' /SILENT', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode);
          sleep(1000);    //Give enough time for the install screen to be repainted before continuing
        end
  end;
end;
