;
; ASCOM Lumix Camera driver - 32-bit installer
; Originally generated by the ASCOM Driver Installer Script Generator 6.4.0.0
;
; Build with:  ISCC "ASCOM.Lumix.Camera Setup32.iss"
; Requires the x86 Release build first:
;   msbuild LumixCamera\LumixCamera.vbproj -p:Configuration=Release -p:Platform=x86 -p:RegisterForComInterop=false
;   (the installer registers the assembly itself, and registering during an x86 build
;    fails while an x64 build output is present - MSB3097)
;
; WI-FI ONLY. The Lumix USB SDK Panasonic ships is x64 only, so a 32-bit host cannot
; load it. This build therefore has no USB transport: the setup dialog reports
; "USB cam: none" and the USB modes cannot connect. Use the 64-bit installer for USB.
;
; Shares its AppID with the 64-bit installer on purpose - they are two builds of the
; same driver installing to the same folder, so installing one replaces the other.
;

#define AppVer "8.0.0"
; Paths are relative to this .iss file so the script builds on any machine.
#define RepoRoot AddBackslash(SourcePath) + "..\"
#define BinDir   AddBackslash(SourcePath) + "bin\x86\Release\"

[Setup]
AppID={{77b4d898-3116-40a5-91d4-4c41ff123d93}
AppName=ASCOM Lumix Camera Driver
AppVerName=ASCOM Lumix Camera Driver {#AppVer} (32-bit, Wi-Fi only)
AppVersion={#AppVer}
AppPublisher=robert hasson <robert_hasson@yahoo.com>
AppPublisherURL=mailto:robert_hasson@yahoo.com
AppSupportURL=http://tech.groups.yahoo.com/group/ASCOM-Talk/
AppUpdatesURL=http://ascom-standards.org/
VersionInfoVersion={#AppVer}
MinVersion=0,6.0
DefaultDirName="{cf}\ASCOM\Camera"
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputBaseFilename="ASCOM.Lumix.Camera Setup32"
Compression=lzma
SolidCompression=yes
; Put there by Platform if Driver Installer Support selected
WizardImageFile="C:\Program Files (x86)\ASCOM\Developer\Installer Generator\Resources\WizardImage.bmp"
LicenseFile="C:\Program Files (x86)\ASCOM\Developer\Installer Generator\Resources\CreativeCommons.txt"
; {cf}\ASCOM\Uninstall\Camera folder created by Platform, always
UninstallFilesDir="{cf}\ASCOM\Uninstall\Camera\ASCOM.Lumix.Camera"
OutputDir="{#RepoRoot}"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{cf}\ASCOM\Uninstall\Camera\ASCOM.Lumix.Camera"

[Files]
Source: "{#BinDir}ASCOM.Lumix.Camera.dll"; DestDir: "{app}"
; Shipped so the assembly loads. With no x86 Lmxptpif.dll beside it the USB modes
; report the SDK as missing rather than failing obscurely.
Source: "{#BinDir}ASCOM.Lumix.Usb.dll"; DestDir: "{app}"
; RAW decoding
Source: "{#BinDir}libraw.dll"; DestDir: "{app}"
Source: "{#BinDir}libraw32.dll"; DestDir: "{app}"
; Read-me shown after installation
Source: "{#RepoRoot}README.md"; DestDir: "{app}"; Flags: isreadme
Source: "{#RepoRoot}readme_files\*"; DestDir: "{app}\readme_files\"

; Only for .NET assembly/in-proc drivers.
; NOTE: only the driver assembly is registered. libraw/libraw32 are native DLLs -
; running regasm on them was a no-op that could only ever fail.
[Run]
Filename: "{dotnet4032}\regasm.exe"; Parameters: "/codebase ""{app}\ASCOM.Lumix.Camera.dll"""; Flags: runhidden 32bit

[UninstallRun]
Filename: "{dotnet4032}\regasm.exe"; Parameters: "-u ""{app}\ASCOM.Lumix.Camera.dll"""; Flags: runhidden 32bit

[Code]
const
   REQUIRED_PLATFORM_VERSION = 6.2;    // Set this to the minimum required ASCOM Platform version for this application

//
// Function to return the ASCOM Platform's version number as a double.
//
function PlatformVersion(): Double;
var
   PlatVerString : String;
begin
   Result := 0.0;  // Initialise the return value in case we can't read the registry
   try
      if RegQueryStringValue(HKEY_LOCAL_MACHINE_32, 'Software\ASCOM','PlatformVersion', PlatVerString) then
      begin // Successfully read the value from the registry
         Result := StrToFloat(PlatVerString); // Create a double from the X.Y Platform version string
      end;
   except
      ShowExceptionMessage;
      Result:= -1.0; // Indicate in the return value that an exception was generated
   end;
end;

//
// Before the installer UI appears, verify that the required ASCOM Platform version is installed.
//
function InitializeSetup(): Boolean;
var
   PlatformVersionNumber : double;
 begin
   Result := FALSE;  // Assume failure
   PlatformVersionNumber := PlatformVersion(); // Get the installed Platform version as a double
   If PlatformVersionNumber >= REQUIRED_PLATFORM_VERSION then	// Check whether we have the minimum required Platform or newer
      Result := TRUE
   else
      if PlatformVersionNumber = 0.0 then
         MsgBox('No ASCOM Platform is installed. Please install Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later from http://www.ascom-standards.org', mbCriticalError, MB_OK)
      else
         MsgBox('ASCOM Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later is required, but Platform '+ Format('%3.1f', [PlatformVersionNumber]) + ' is installed. Please install the latest Platform before continuing; you will find it at http://www.ascom-standards.org', mbCriticalError, MB_OK);
end;

// Code to enable the installer to uninstall previous versions of itself when a new version is installed
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  UninstallExe: String;
  UninstallRegistry: String;
begin
  if (CurStep = ssInstall) then // Install step has started
	begin
      // Create the correct registry location name, which is based on the AppId
      UninstallRegistry := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}' + '_is1');
      // Check whether an extry exists
      if RegQueryStringValue(HKLM, UninstallRegistry, 'UninstallString', UninstallExe) then
        begin // Entry exists and previous version is installed so run its uninstaller quietly after informing the user
          MsgBox('Setup will now remove the previous version.', mbInformation, MB_OK);
          Exec(RemoveQuotes(UninstallExe), ' /SILENT', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode);
          sleep(1000);    //Give enough time for the install screen to be repainted before continuing
        end
  end;
end;
